"""C2 analysis notes generated from the instructions: a mechanical transcription of one function (every memory access
with width and direction, every conditional branch with its signedness, every callee, every constant, each cited with
the address of the instruction), in the layout re/CONFIDENCE.md requires for C2 (`## Signature`, `## Reads`,
`## Writes`, `## Callees`, `## Constants`). Nothing here interprets the code: registers are cited by name, fields as
`[reg+0xNN]`; the role of the function comes from its names row and its system writeup, both linked.

    py -3.12 re/tools/c2_note.py --module sound.dll 0x10019770        # print one note
    py -3.12 re/tools/c2_note.py --all --out log/c2_batch.tsv          # write notes for every C1 row of hooks.csv
                                                                       # that has none, plus a TSV for
                                                                       # `re_classify.py batch <tsv> --to C2`
Hand-written notes (any existing file for the address) are never overwritten."""
import argparse, collections, csv, glob, pathlib, re, sys

import capstone
from capstone import x86

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import xref  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
SIGNED = {"jl", "jle", "jg", "jge", "js", "jns", "jo", "jno"}
UNSIGNED = {"jb", "jbe", "ja", "jae"}
EQUAL = {"je", "jne"}
WIDTH = {1: "byte", 2: "word", 4: "dword", 8: "qword", 10: "tword", 16: "xmmword"}
GEN = "generated by re/tools/c2_note.py"


def hexa(v):
    return f"0x{v:08x}"


def match_sources():
    out = {}
    for f in glob.glob(str(ROOT / "re" / "match" / "*.cpp")):
        for mod, a, sym in re.findall(r"//\s*MATCH:\s*(\S+)\s+(0x[0-9a-fA-F]+)\s+(\S+)", open(f, errors="replace").read()):
            out.setdefault((mod, int(a, 16)), (pathlib.Path(f).name, sym))
    return out


def systems_index():
    idx = collections.defaultdict(list)
    for f in sorted(glob.glob(str(ROOT / "re" / "analysis" / "systems" / "*.md"))):
        for a in set(re.findall(r"0x([0-9a-fA-F]{8})", open(f, encoding="utf-8").read())):
            idx[int(a, 16)].append(pathlib.Path(f).relative_to(ROOT).as_posix())
    return idx


def names_rows():
    out = {}
    for f in glob.glob(str(ROOT / "re" / "names" / "*.tsv")):
        if f.endswith("_globals.tsv") or f.endswith("withdrawn.tsv"):
            continue
        for l in open(f, encoding="utf-8").read().splitlines()[1:]:
            c = l.split("\t")
            if len(c) == 6:
                out[(c[0], int(c[1], 16))] = (pathlib.Path(f).relative_to(ROOT).as_posix(), c[5])
    return out


def hand_notes():
    """Hand-written analysis notes (not generated) by the 8-hex-digit address prefix of their file name."""
    out = collections.defaultdict(list)
    for f in glob.glob(str(ROOT / "re" / "analysis" / "*" / "*.md")):
        m = re.match(r"([0-9a-f]{8})_", pathlib.Path(f).name)
        if m and GEN not in open(f, encoding="utf-8").read(400):
            out[int(m.group(1), 16)].append(pathlib.Path(f).relative_to(ROOT).as_posix())
    return out


class Ctx:
    def __init__(self):
        self.match = match_sources()
        self.systems = systems_index()
        self.namerows = names_rows()
        self.hand = hand_notes()
        self.pe, self.idx, self.iat, self.base = {}, {}, {}, {}

    def module(self, mod):
        if mod not in self.pe:
            pe, base = xref.load_pe(mod)
            pe.parse_data_directories()            # load_pe is fast_load: imports are not parsed yet
            self.pe[mod], self.base[mod], self.idx[mod] = pe, base, xref.load(mod)
            self.iat[mod] = {i.address: (e.dll.decode(), (i.name or b"#%d" % i.ordinal).decode())
                             for e in getattr(pe, "DIRECTORY_ENTRY_IMPORT", []) for i in e.imports}
        return self.pe[mod], self.base[mod], self.idx[mod], self.iat[mod]


def thunk_target(pe, base, va):
    """Body of a 5-byte `jmp rel32` thunk at va (debug builds call through them), else None."""
    try:
        b = pe.get_data(va - base, 5)
    except Exception:
        return None
    if len(b) == 5 and b[0] == 0xE9:
        return (va + 5 + int.from_bytes(b[1:5], "little", signed=True)) & 0xFFFFFFFF
    return None


def operand_text(ins, op):
    m = op.mem
    parts = []
    if m.base:
        parts.append(ins.reg_name(m.base))
    if m.index:
        parts.append(f"{ins.reg_name(m.index)}*{m.scale}" if m.scale != 1 else ins.reg_name(m.index))
    d = m.disp
    if parts:
        s = "+".join(parts) + (f"+0x{d:x}" if d > 0 else (f"-0x{-d:x}" if d < 0 else ""))
    else:
        s = hexa(d & 0xFFFFFFFF)
    seg = ins.reg_name(m.segment) + ":" if m.segment else ""
    return f"{seg}[{s}]"


def addr_list(addrs, limit=8):
    a = sorted(set(addrs))
    s = ", ".join(hexa(x) for x in a[:limit])
    return s + (f" (+{len(a) - limit} more)" if len(a) > limit else "")


def note(ctx, mod, va, name, subsystem):
    pe, base, idx, iat = ctx.module(mod)
    fn = idx.get(va)
    size = fn["size"] if fn else None
    if size is None:
        return None
    code = pe.get_data(va - base, size)
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
    md.detail = True
    insns = list(md.disasm(code, va))
    entries = set(idx)
    names = {a: f["name"] for a, f in idx.items()}
    img_lo, img_hi = base, base + pe.OPTIONAL_HEADER.SizeOfImage

    reads, writes = collections.defaultdict(list), collections.defaultdict(list)
    ext = {}                                   # operand -> movsx/movzx
    branches = collections.defaultdict(list)
    callees, indirect, imports = collections.defaultdict(list), collections.defaultdict(list), collections.defaultdict(list)
    consts = collections.defaultdict(list)
    rets = []
    first_touch = {}                           # reg -> ("read"|"write", addr) in address order
    for ins in insns:
        try:
            rr, ww = ins.regs_access()
        except capstone.CsError:
            rr, ww = [], []
        for r in ("ecx", "edx", "eax"):
            if r in first_touch:
                continue
            rd = {ins.reg_name(x) for x in rr}
            wr = {ins.reg_name(x) for x in ww}
            fam = {"ecx": {"ecx", "cx", "cl", "ch"}, "edx": {"edx", "dx", "dl", "dh"}, "eax": {"eax", "ax", "al", "ah"}}[r]
            if ins.mnemonic in ("xor", "sub") and len(ins.operands) == 2 and ins.operands[0].type == x86.X86_OP_REG \
                    and ins.operands[1].type == x86.X86_OP_REG and ins.operands[0].reg == ins.operands[1].reg \
                    and ins.reg_name(ins.operands[0].reg) in fam:
                first_touch[r] = ("write", ins.address)
            elif rd & fam:
                first_touch[r] = ("read", ins.address)
            elif wr & fam:
                first_touch[r] = ("write", ins.address)
        mn = ins.mnemonic
        if mn.startswith("ret"):
            rets.append((ins.address, ins.operands[0].imm if ins.operands else 0))
        if mn in ("call", "jmp") and ins.operands:
            op = ins.operands[0]
            if op.type == x86.X86_OP_IMM:
                t = op.imm & 0xFFFFFFFF
                if mn == "call" or not (va <= t < va + size):
                    callees[t].append(ins.address)
                continue
            if op.type == x86.X86_OP_MEM and not op.mem.base and not op.mem.index:
                t = op.mem.disp & 0xFFFFFFFF
                if t in iat:
                    imports[iat[t]].append(ins.address)
                    continue
            if op.type in (x86.X86_OP_MEM, x86.X86_OP_REG):
                indirect[(mn, operand_text(ins, op) if op.type == x86.X86_OP_MEM else ins.reg_name(op.reg))].append(ins.address)
                if op.type == x86.X86_OP_MEM:
                    reads[(operand_text(ins, op), op.size)].append(ins.address)
                continue
        if mn.startswith("j") and mn != "jmp":
            kind = "signed" if mn in SIGNED else "unsigned" if mn in UNSIGNED else "equality" if mn in EQUAL else "flag"
            branches[(mn, kind)].append(ins.address)
        for i, op in enumerate(ins.operands):
            if op.type == x86.X86_OP_MEM:
                if mn == "lea":
                    if op.mem.disp:
                        consts[op.mem.disp & 0xFFFFFFFF].append(ins.address)
                    continue
                if mn == "nop":
                    continue
                key = (operand_text(ins, op), op.size)
                acc = op.access
                if acc & capstone.CS_AC_READ or (not acc and i > 0):
                    reads[key].append(ins.address)
                if acc & capstone.CS_AC_WRITE or (not acc and i == 0 and len(ins.operands) > 1):
                    writes[key].append(ins.address)
                if mn in ("movsx", "movzx"):
                    ext[key] = "sign-extended" if mn == "movsx" else "zero-extended"
                d = op.mem.disp & 0xFFFFFFFF
                if not op.mem.base and not op.mem.index and img_lo <= d < img_hi:
                    continue
            elif op.type == x86.X86_OP_IMM:
                v = op.imm & 0xFFFFFFFF
                if mn in ("call", "jmp") or mn.startswith("j") or mn.startswith("ret"):
                    continue
                consts[v].append(ins.address)

    rva = va - base if mod != "golf_clean.exe" else va
    L = [f"# {hexa(va)} {name}", "",
         f"Module `{mod}`" + (f" (RVA `0x{rva:08x}`)" if mod != "golf_clean.exe" else "") +
         f", {size} bytes, {len(insns)} instructions, subsystem `{subsystem}`. Mechanical transcription {GEN} "
         f"from the anchored binary; registers are cited by name and fields as `[reg+0xNN]`.", ""]
    nr = ctx.namerows.get((mod, va))
    if nr:
        L += ["## Role (from the naming pass, not a C3 purpose)", f"{nr[1]} (`{nr[0]}`)"]
        sy = ctx.systems.get(va)
        if sy:
            L.append("System writeup: " + ", ".join(f"`{s}`" for s in sy) + ".")
        L.append("")
    hand = ctx.hand.get(rva)
    if hand:
        L += ["Hand-written analysis of this function: " + ", ".join(f"`{h}`" for h in hand) + ".", ""]

    L.append("## Signature")
    m = ctx.match.get((mod, va))
    if m:
        L.append(f"- Matched at 100% by `re/match/{m[0]}` as `{m[1]}`" + (
            " (the decorated name fixes the exact C++ signature and convention)." if m[1].startswith("?")
            else " (C linkage: the source declares the signature)."))
    if rets:
        pops = sorted({n for _, n in rets})
        L.append("- Returns with " + ", ".join(f"`ret{(' 0x%x' % n) if n else ''}`" for n in pops) +
                 f" (at {addr_list([a for a, _ in rets])}): callee pops {', '.join(str(n) for n in pops)} bytes of stack arguments.")
    else:
        L.append("- No `ret` inside the extent (tail jump or noreturn call ends it).")
    for r, role in (("ecx", "`this` (thiscall) or the first fastcall argument"), ("edx", "the second fastcall argument")):
        t = first_touch.get(r)
        if t and t[0] == "read":
            L.append(f"- `{r}` is read at {hexa(t[1])} before any write in address order: an input register ({role}).")
    if any(i.mnemonic == "mov" and i.op_str in ("dword ptr [ebp - 4], ecx",) for i in insns[:12]):
        L.append("- Debug prologue stores `ecx` to `[ebp-4]` (VC6 /Od thiscall pattern).")
    L.append("")

    def access_lines(d, label):
        if not d:
            return ["None."]
        out = []
        glob_, frame, stack, other = [], [], [], []
        for (o, sz), addrs in sorted(d.items(), key=lambda kv: kv[0][0]):
            w = WIDTH.get(sz, f"{sz}-byte")
            e = f", {ext[(o, sz)]}" if (o, sz) in ext and label == "read" else ""
            line = f"- `{o}` {w}{e} at {addr_list(addrs)}"
            if o.startswith("[0x") or ":[0x" in o:
                glob_.append(line)
            elif o.startswith("[ebp"):
                frame.append(line)
            elif o.startswith("[esp"):
                stack.append(line)
            else:
                other.append(line)
        if glob_:
            out += ["Globals:"] + glob_
        if other:
            out += ["Through registers:"] + other
        if frame:
            out += ["Frame (`ebp`: positive = arguments, negative = locals):"] + frame
        if stack:
            out += ["Stack (`esp`-relative; offsets shift with pushes):"] + stack
        return out

    L += ["## Reads"] + access_lines(reads, "read") + [""]
    L += ["## Writes"] + access_lines(writes, "write") + [""]
    if branches:
        L.append("## Branches")
        for (mn, kind), addrs in sorted(branches.items()):
            L.append(f"- `{mn}` ({kind}) at {addr_list(addrs)}")
        L.append("")

    L.append("## Callees")
    if not (callees or imports or indirect):
        L.append("None (leaf).")
    for t, addrs in sorted(callees.items()):
        body = thunk_target(pe, base, t)
        if body is not None and body in entries:
            L.append(f"- {hexa(t)} -> {hexa(body)} `{names.get(body, '?')}` (incremental-linking thunk) at {addr_list(addrs)}")
            continue
        nm = names.get(t, "?")
        L.append(f"- {hexa(t)} `{nm}` at {addr_list(addrs)}" + ("" if t in entries else " (not a function entry)"))
    for (dll, api), addrs in sorted(imports.items()):
        L.append(f"- import `{dll}!{api}` at {addr_list(addrs)}")
    for (mn, o), addrs in sorted(indirect.items()):
        L.append(f"- indirect `{mn} {o}` at {addr_list(addrs)}")
    L.append("")
    callers = fn.get("callers") or []
    L.append("## Callers")
    L.append(("None found by direct call (static); indirect callers are not resolved here." if not callers else
              ", ".join(f"{hexa(c)} `{names.get(c, '?')}`" for c in callers[:20]) + (f" (+{len(callers) - 20} more)" if len(callers) > 20 else "")))
    L.append("")

    L.append("## Constants")
    if not consts:
        L.append("None.")
    for v, addrs in sorted(consts.items()):
        sv = v - (1 << 32) if v & 0x80000000 else v
        kind = ""
        if img_lo <= v < img_hi:
            if v in entries:
                kind = f" = function `{names.get(v, '?')}`"
            elif xref.read_cstr(pe, base, v) is not None:
                kind = " = address of a string (text not reproduced)"
            else:
                kind = " = address in the image (data)"
        signed = f" ({sv})" if sv < 0 else f" ({v})" if v > 9 else ""
        L.append(f"- `0x{v:x}`{signed}{kind} at {addr_list(addrs)}")
    L.append("")
    resolved = set()
    for c in callees:
        body = thunk_target(pe, base, c)
        resolved.add(body if body in entries else c)
    return "\n".join(L), callers, sorted(resolved)


def note_path(mod, rva, name, subsystem):
    safe = re.sub(r"[^A-Za-z0-9_]+", "_", name).strip("_")[:60]
    prefix = "" if mod == "golf_clean.exe" else {"Terrain.dll": "TerrainDll_", "jgld.dll": "jgld_", "sound.dll": "sound_"}[mod]
    return pathlib.Path("re") / "analysis" / subsystem / f"{rva:08x}_{prefix}{safe}.md"


def existing_note(row):
    """The row's note when it must not be regenerated: hand-written, or carrying a hand `## Purpose`."""
    n = row.get("note") or ""
    if not (n and (ROOT / n).is_file()):
        return None
    text = (ROOT / n).read_text(encoding="utf-8")
    return n if (GEN not in text or "## Purpose" in text) else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("addr", nargs="?")
    ap.add_argument("--module", default="golf_clean.exe")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--out", default="log/c2_batch.tsv")
    ap.add_argument("--limit", type=int)
    a = ap.parse_args()
    ctx = Ctx()
    if a.addr:
        va = int(a.addr, 16)
        base = 0 if a.module == "golf_clean.exe" else 0x10000000
        va = va if va >= base else va + base
        r = ctx.module(a.module)
        nm = r[2].get(va, {}).get("name", "?")
        print(note(ctx, a.module, va, nm, "unknown")[0])
        return 0
    rows = list(csv.DictReader(open(ROOT / "hooks.csv", newline="")))
    out = ["module\taddr\tname\tsubsystem\tnote\tcallers\tcallees"]
    written = skipped = 0
    for row in rows:
        if (row.get("confidence") or "C0") != "C1":
            continue
        mod = row.get("module") or "golf_clean.exe"
        rva = int(row["addr"], 16)
        va = rva if mod == "golf_clean.exe" else rva + 0x10000000
        path = existing_note(row)
        if not path:
            res = note(ctx, mod, va, row["name"], row["subsystem"])
            if res is None:
                skipped += 1
                continue
            text, callers, callees = res
            p = note_path(mod, rva, row["name"], row["subsystem"])
            if (ROOT / p).exists():
                old = (ROOT / p).read_text(encoding="utf-8")
                if GEN not in old or "## Purpose" in old:
                    skipped += 1                   # hand-written, or a generated note given a hand Purpose (C3)
                    continue
            (ROOT / p).parent.mkdir(parents=True, exist_ok=True)
            (ROOT / p).write_text(text, encoding="utf-8")
            path = p.as_posix()
            written += 1
        else:
            _, _, idx, _ = ctx.module(mod)
            f = idx.get(va) or {}
            callers, callees = f.get("callers", []), f.get("calls", [])
        cl = ";".join(hexa(c) for c in callers) or "none"
        ce = ";".join(hexa(c) for c in callees) or "none"
        out.append(f"{mod}\t{hexa(va)}\t{row['name']}\t{row['subsystem']}\t{path}\t{cl}\t{ce}")
        if a.limit and written >= a.limit:
            break
    (ROOT / a.out).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{written} notes written, {skipped} skipped, {len(out) - 1} rows -> {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
