"""Generate the winmm.dll proxy (export stubs that jump into the real SysWOW64 winmm).
Re-run if Windows updates winmm's export table: py -3.12 shim/gen_winmm_proxy.py"""
import pathlib
import pefile

HERE = pathlib.Path(__file__).parent
pe = pefile.PE(r"C:\Windows\SysWOW64\winmm.dll", fast_load=True)
pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])
exports = [(e.ordinal, e.name.decode()) for e in pe.DIRECTORY_ENTRY_EXPORT.symbols if e.name]

c = ["// GENERATED by gen_winmm_proxy.py -- do not edit.",
     "#include <windows.h>",
     f"#define WINMM_EXPORT_COUNT {len(exports)}",
     "FARPROC g_winmm[WINMM_EXPORT_COUNT];",
     "static const char* const s_winmmNames[WINMM_EXPORT_COUNT] = {"]
c += [f'    "{n}",' for _, n in exports]
c += ["};",
      "void WinmmProxyResolve(HMODULE real) {",
      "    for (int i = 0; i < WINMM_EXPORT_COUNT; ++i) g_winmm[i] = GetProcAddress(real, s_winmmNames[i]);",
      "}"]
for i, (_, n) in enumerate(exports):
    c.append(f"extern \"C\" __declspec(naked) void p_{n}() {{ __asm jmp dword ptr [g_winmm + {i * 4}] }}")
(HERE / "src" / "winmm_proxy.gen.cpp").write_text("\n".join(c) + "\n")

d = ["LIBRARY winmm", "EXPORTS"]
d += [f"    {n}=p_{n} @{o}" for o, n in exports]
d += ["    SimGolfShim_SetVirtualCursor", "    SimGolfShim_ClearVirtualCursor", "    SimGolfShim_GetInfo", "    SimGolfShim_FindHook", "    SimGolfShim_CovPhase", "    SimGolfShim_CovDump", "    SimGolfShim_SetVirtualKey"]
(HERE / "src" / "winmm.def").write_text("\n".join(d) + "\n")
print(len(exports), "exports")
