// GENERATED by gen_winmm_proxy.py -- do not edit.
#include <windows.h>
#define WINMM_EXPORT_COUNT 192
FARPROC g_winmm[WINMM_EXPORT_COUNT];
static const char* const s_winmmNames[WINMM_EXPORT_COUNT] = {
    "CloseDriver",
    "DefDriverProc",
    "DriverCallback",
    "DrvGetModuleHandle",
    "GetDriverModuleHandle",
    "NotifyCallbackData",
    "OpenDriver",
    "PlaySound",
    "PlaySoundA",
    "PlaySoundW",
    "SendDriverMessage",
    "WOW32DriverCallback",
    "WOW32ResolveMultiMediaHandle",
    "WOWAppExit",
    "aux32Message",
    "auxGetDevCapsA",
    "auxGetDevCapsW",
    "auxGetNumDevs",
    "auxGetVolume",
    "auxOutMessage",
    "auxSetVolume",
    "joy32Message",
    "joyConfigChanged",
    "joyGetDevCapsA",
    "joyGetDevCapsW",
    "joyGetNumDevs",
    "joyGetPos",
    "joyGetPosEx",
    "joyGetThreshold",
    "joyReleaseCapture",
    "joySetCapture",
    "joySetThreshold",
    "mci32Message",
    "mciDriverNotify",
    "mciDriverYield",
    "mciExecute",
    "mciFreeCommandResource",
    "mciGetCreatorTask",
    "mciGetDeviceIDA",
    "mciGetDeviceIDFromElementIDA",
    "mciGetDeviceIDFromElementIDW",
    "mciGetDeviceIDW",
    "mciGetDriverData",
    "mciGetErrorStringA",
    "mciGetErrorStringW",
    "mciGetYieldProc",
    "mciLoadCommandResource",
    "mciSendCommandA",
    "mciSendCommandW",
    "mciSendStringA",
    "mciSendStringW",
    "mciSetDriverData",
    "mciSetYieldProc",
    "mid32Message",
    "midiConnect",
    "midiDisconnect",
    "midiInAddBuffer",
    "midiInClose",
    "midiInGetDevCapsA",
    "midiInGetDevCapsW",
    "midiInGetErrorTextA",
    "midiInGetErrorTextW",
    "midiInGetID",
    "midiInGetNumDevs",
    "midiInMessage",
    "midiInOpen",
    "midiInPrepareHeader",
    "midiInReset",
    "midiInStart",
    "midiInStop",
    "midiInUnprepareHeader",
    "midiOutCacheDrumPatches",
    "midiOutCachePatches",
    "midiOutClose",
    "midiOutGetDevCapsA",
    "midiOutGetDevCapsW",
    "midiOutGetErrorTextA",
    "midiOutGetErrorTextW",
    "midiOutGetID",
    "midiOutGetNumDevs",
    "midiOutGetVolume",
    "midiOutLongMsg",
    "midiOutMessage",
    "midiOutOpen",
    "midiOutPrepareHeader",
    "midiOutReset",
    "midiOutSetVolume",
    "midiOutShortMsg",
    "midiOutUnprepareHeader",
    "midiStreamClose",
    "midiStreamOpen",
    "midiStreamOut",
    "midiStreamPause",
    "midiStreamPosition",
    "midiStreamProperty",
    "midiStreamRestart",
    "midiStreamStop",
    "mixerClose",
    "mixerGetControlDetailsA",
    "mixerGetControlDetailsW",
    "mixerGetDevCapsA",
    "mixerGetDevCapsW",
    "mixerGetID",
    "mixerGetLineControlsA",
    "mixerGetLineControlsW",
    "mixerGetLineInfoA",
    "mixerGetLineInfoW",
    "mixerGetNumDevs",
    "mixerMessage",
    "mixerOpen",
    "mixerSetControlDetails",
    "mmDrvInstall",
    "mmGetCurrentTask",
    "mmTaskBlock",
    "mmTaskCreate",
    "mmTaskSignal",
    "mmTaskYield",
    "mmioAdvance",
    "mmioAscend",
    "mmioClose",
    "mmioCreateChunk",
    "mmioDescend",
    "mmioFlush",
    "mmioGetInfo",
    "mmioInstallIOProcA",
    "mmioInstallIOProcW",
    "mmioOpenA",
    "mmioOpenW",
    "mmioRead",
    "mmioRenameA",
    "mmioRenameW",
    "mmioSeek",
    "mmioSendMessage",
    "mmioSetBuffer",
    "mmioSetInfo",
    "mmioStringToFOURCCA",
    "mmioStringToFOURCCW",
    "mmioWrite",
    "mmsystemGetVersion",
    "mod32Message",
    "mxd32Message",
    "sndPlaySoundA",
    "sndPlaySoundW",
    "tid32Message",
    "timeBeginPeriod",
    "timeEndPeriod",
    "timeGetDevCaps",
    "timeGetSystemTime",
    "timeGetTime",
    "timeKillEvent",
    "timeSetEvent",
    "waveInAddBuffer",
    "waveInClose",
    "waveInGetDevCapsA",
    "waveInGetDevCapsW",
    "waveInGetErrorTextA",
    "waveInGetErrorTextW",
    "waveInGetID",
    "waveInGetNumDevs",
    "waveInGetPosition",
    "waveInMessage",
    "waveInOpen",
    "waveInPrepareHeader",
    "waveInReset",
    "waveInStart",
    "waveInStop",
    "waveInUnprepareHeader",
    "waveOutBreakLoop",
    "waveOutClose",
    "waveOutGetDevCapsA",
    "waveOutGetDevCapsW",
    "waveOutGetErrorTextA",
    "waveOutGetErrorTextW",
    "waveOutGetID",
    "waveOutGetNumDevs",
    "waveOutGetPitch",
    "waveOutGetPlaybackRate",
    "waveOutGetPosition",
    "waveOutGetVolume",
    "waveOutMessage",
    "waveOutOpen",
    "waveOutPause",
    "waveOutPrepareHeader",
    "waveOutReset",
    "waveOutRestart",
    "waveOutSetPitch",
    "waveOutSetPlaybackRate",
    "waveOutSetVolume",
    "waveOutUnprepareHeader",
    "waveOutWrite",
    "wid32Message",
    "wod32Message",
};
void WinmmProxyResolve(HMODULE real) {
    for (int i = 0; i < WINMM_EXPORT_COUNT; ++i) g_winmm[i] = GetProcAddress(real, s_winmmNames[i]);
}
extern "C" __declspec(naked) void p_CloseDriver() { __asm jmp dword ptr [g_winmm + 0] }
extern "C" __declspec(naked) void p_DefDriverProc() { __asm jmp dword ptr [g_winmm + 4] }
extern "C" __declspec(naked) void p_DriverCallback() { __asm jmp dword ptr [g_winmm + 8] }
extern "C" __declspec(naked) void p_DrvGetModuleHandle() { __asm jmp dword ptr [g_winmm + 12] }
extern "C" __declspec(naked) void p_GetDriverModuleHandle() { __asm jmp dword ptr [g_winmm + 16] }
extern "C" __declspec(naked) void p_NotifyCallbackData() { __asm jmp dword ptr [g_winmm + 20] }
extern "C" __declspec(naked) void p_OpenDriver() { __asm jmp dword ptr [g_winmm + 24] }
extern "C" __declspec(naked) void p_PlaySound() { __asm jmp dword ptr [g_winmm + 28] }
extern "C" __declspec(naked) void p_PlaySoundA() { __asm jmp dword ptr [g_winmm + 32] }
extern "C" __declspec(naked) void p_PlaySoundW() { __asm jmp dword ptr [g_winmm + 36] }
extern "C" __declspec(naked) void p_SendDriverMessage() { __asm jmp dword ptr [g_winmm + 40] }
extern "C" __declspec(naked) void p_WOW32DriverCallback() { __asm jmp dword ptr [g_winmm + 44] }
extern "C" __declspec(naked) void p_WOW32ResolveMultiMediaHandle() { __asm jmp dword ptr [g_winmm + 48] }
extern "C" __declspec(naked) void p_WOWAppExit() { __asm jmp dword ptr [g_winmm + 52] }
extern "C" __declspec(naked) void p_aux32Message() { __asm jmp dword ptr [g_winmm + 56] }
extern "C" __declspec(naked) void p_auxGetDevCapsA() { __asm jmp dword ptr [g_winmm + 60] }
extern "C" __declspec(naked) void p_auxGetDevCapsW() { __asm jmp dword ptr [g_winmm + 64] }
extern "C" __declspec(naked) void p_auxGetNumDevs() { __asm jmp dword ptr [g_winmm + 68] }
extern "C" __declspec(naked) void p_auxGetVolume() { __asm jmp dword ptr [g_winmm + 72] }
extern "C" __declspec(naked) void p_auxOutMessage() { __asm jmp dword ptr [g_winmm + 76] }
extern "C" __declspec(naked) void p_auxSetVolume() { __asm jmp dword ptr [g_winmm + 80] }
extern "C" __declspec(naked) void p_joy32Message() { __asm jmp dword ptr [g_winmm + 84] }
extern "C" __declspec(naked) void p_joyConfigChanged() { __asm jmp dword ptr [g_winmm + 88] }
extern "C" __declspec(naked) void p_joyGetDevCapsA() { __asm jmp dword ptr [g_winmm + 92] }
extern "C" __declspec(naked) void p_joyGetDevCapsW() { __asm jmp dword ptr [g_winmm + 96] }
extern "C" __declspec(naked) void p_joyGetNumDevs() { __asm jmp dword ptr [g_winmm + 100] }
extern "C" __declspec(naked) void p_joyGetPos() { __asm jmp dword ptr [g_winmm + 104] }
extern "C" __declspec(naked) void p_joyGetPosEx() { __asm jmp dword ptr [g_winmm + 108] }
extern "C" __declspec(naked) void p_joyGetThreshold() { __asm jmp dword ptr [g_winmm + 112] }
extern "C" __declspec(naked) void p_joyReleaseCapture() { __asm jmp dword ptr [g_winmm + 116] }
extern "C" __declspec(naked) void p_joySetCapture() { __asm jmp dword ptr [g_winmm + 120] }
extern "C" __declspec(naked) void p_joySetThreshold() { __asm jmp dword ptr [g_winmm + 124] }
extern "C" __declspec(naked) void p_mci32Message() { __asm jmp dword ptr [g_winmm + 128] }
extern "C" __declspec(naked) void p_mciDriverNotify() { __asm jmp dword ptr [g_winmm + 132] }
extern "C" __declspec(naked) void p_mciDriverYield() { __asm jmp dword ptr [g_winmm + 136] }
extern "C" __declspec(naked) void p_mciExecute() { __asm jmp dword ptr [g_winmm + 140] }
extern "C" __declspec(naked) void p_mciFreeCommandResource() { __asm jmp dword ptr [g_winmm + 144] }
extern "C" __declspec(naked) void p_mciGetCreatorTask() { __asm jmp dword ptr [g_winmm + 148] }
extern "C" __declspec(naked) void p_mciGetDeviceIDA() { __asm jmp dword ptr [g_winmm + 152] }
extern "C" __declspec(naked) void p_mciGetDeviceIDFromElementIDA() { __asm jmp dword ptr [g_winmm + 156] }
extern "C" __declspec(naked) void p_mciGetDeviceIDFromElementIDW() { __asm jmp dword ptr [g_winmm + 160] }
extern "C" __declspec(naked) void p_mciGetDeviceIDW() { __asm jmp dword ptr [g_winmm + 164] }
extern "C" __declspec(naked) void p_mciGetDriverData() { __asm jmp dword ptr [g_winmm + 168] }
extern "C" __declspec(naked) void p_mciGetErrorStringA() { __asm jmp dword ptr [g_winmm + 172] }
extern "C" __declspec(naked) void p_mciGetErrorStringW() { __asm jmp dword ptr [g_winmm + 176] }
extern "C" __declspec(naked) void p_mciGetYieldProc() { __asm jmp dword ptr [g_winmm + 180] }
extern "C" __declspec(naked) void p_mciLoadCommandResource() { __asm jmp dword ptr [g_winmm + 184] }
extern "C" __declspec(naked) void p_mciSendCommandA() { __asm jmp dword ptr [g_winmm + 188] }
extern "C" __declspec(naked) void p_mciSendCommandW() { __asm jmp dword ptr [g_winmm + 192] }
extern "C" __declspec(naked) void p_mciSendStringA() { __asm jmp dword ptr [g_winmm + 196] }
extern "C" __declspec(naked) void p_mciSendStringW() { __asm jmp dword ptr [g_winmm + 200] }
extern "C" __declspec(naked) void p_mciSetDriverData() { __asm jmp dword ptr [g_winmm + 204] }
extern "C" __declspec(naked) void p_mciSetYieldProc() { __asm jmp dword ptr [g_winmm + 208] }
extern "C" __declspec(naked) void p_mid32Message() { __asm jmp dword ptr [g_winmm + 212] }
extern "C" __declspec(naked) void p_midiConnect() { __asm jmp dword ptr [g_winmm + 216] }
extern "C" __declspec(naked) void p_midiDisconnect() { __asm jmp dword ptr [g_winmm + 220] }
extern "C" __declspec(naked) void p_midiInAddBuffer() { __asm jmp dword ptr [g_winmm + 224] }
extern "C" __declspec(naked) void p_midiInClose() { __asm jmp dword ptr [g_winmm + 228] }
extern "C" __declspec(naked) void p_midiInGetDevCapsA() { __asm jmp dword ptr [g_winmm + 232] }
extern "C" __declspec(naked) void p_midiInGetDevCapsW() { __asm jmp dword ptr [g_winmm + 236] }
extern "C" __declspec(naked) void p_midiInGetErrorTextA() { __asm jmp dword ptr [g_winmm + 240] }
extern "C" __declspec(naked) void p_midiInGetErrorTextW() { __asm jmp dword ptr [g_winmm + 244] }
extern "C" __declspec(naked) void p_midiInGetID() { __asm jmp dword ptr [g_winmm + 248] }
extern "C" __declspec(naked) void p_midiInGetNumDevs() { __asm jmp dword ptr [g_winmm + 252] }
extern "C" __declspec(naked) void p_midiInMessage() { __asm jmp dword ptr [g_winmm + 256] }
extern "C" __declspec(naked) void p_midiInOpen() { __asm jmp dword ptr [g_winmm + 260] }
extern "C" __declspec(naked) void p_midiInPrepareHeader() { __asm jmp dword ptr [g_winmm + 264] }
extern "C" __declspec(naked) void p_midiInReset() { __asm jmp dword ptr [g_winmm + 268] }
extern "C" __declspec(naked) void p_midiInStart() { __asm jmp dword ptr [g_winmm + 272] }
extern "C" __declspec(naked) void p_midiInStop() { __asm jmp dword ptr [g_winmm + 276] }
extern "C" __declspec(naked) void p_midiInUnprepareHeader() { __asm jmp dword ptr [g_winmm + 280] }
extern "C" __declspec(naked) void p_midiOutCacheDrumPatches() { __asm jmp dword ptr [g_winmm + 284] }
extern "C" __declspec(naked) void p_midiOutCachePatches() { __asm jmp dword ptr [g_winmm + 288] }
extern "C" __declspec(naked) void p_midiOutClose() { __asm jmp dword ptr [g_winmm + 292] }
extern "C" __declspec(naked) void p_midiOutGetDevCapsA() { __asm jmp dword ptr [g_winmm + 296] }
extern "C" __declspec(naked) void p_midiOutGetDevCapsW() { __asm jmp dword ptr [g_winmm + 300] }
extern "C" __declspec(naked) void p_midiOutGetErrorTextA() { __asm jmp dword ptr [g_winmm + 304] }
extern "C" __declspec(naked) void p_midiOutGetErrorTextW() { __asm jmp dword ptr [g_winmm + 308] }
extern "C" __declspec(naked) void p_midiOutGetID() { __asm jmp dword ptr [g_winmm + 312] }
extern "C" __declspec(naked) void p_midiOutGetNumDevs() { __asm jmp dword ptr [g_winmm + 316] }
extern "C" __declspec(naked) void p_midiOutGetVolume() { __asm jmp dword ptr [g_winmm + 320] }
extern "C" __declspec(naked) void p_midiOutLongMsg() { __asm jmp dword ptr [g_winmm + 324] }
extern "C" __declspec(naked) void p_midiOutMessage() { __asm jmp dword ptr [g_winmm + 328] }
extern "C" __declspec(naked) void p_midiOutOpen() { __asm jmp dword ptr [g_winmm + 332] }
extern "C" __declspec(naked) void p_midiOutPrepareHeader() { __asm jmp dword ptr [g_winmm + 336] }
extern "C" __declspec(naked) void p_midiOutReset() { __asm jmp dword ptr [g_winmm + 340] }
extern "C" __declspec(naked) void p_midiOutSetVolume() { __asm jmp dword ptr [g_winmm + 344] }
extern "C" __declspec(naked) void p_midiOutShortMsg() { __asm jmp dword ptr [g_winmm + 348] }
extern "C" __declspec(naked) void p_midiOutUnprepareHeader() { __asm jmp dword ptr [g_winmm + 352] }
extern "C" __declspec(naked) void p_midiStreamClose() { __asm jmp dword ptr [g_winmm + 356] }
extern "C" __declspec(naked) void p_midiStreamOpen() { __asm jmp dword ptr [g_winmm + 360] }
extern "C" __declspec(naked) void p_midiStreamOut() { __asm jmp dword ptr [g_winmm + 364] }
extern "C" __declspec(naked) void p_midiStreamPause() { __asm jmp dword ptr [g_winmm + 368] }
extern "C" __declspec(naked) void p_midiStreamPosition() { __asm jmp dword ptr [g_winmm + 372] }
extern "C" __declspec(naked) void p_midiStreamProperty() { __asm jmp dword ptr [g_winmm + 376] }
extern "C" __declspec(naked) void p_midiStreamRestart() { __asm jmp dword ptr [g_winmm + 380] }
extern "C" __declspec(naked) void p_midiStreamStop() { __asm jmp dword ptr [g_winmm + 384] }
extern "C" __declspec(naked) void p_mixerClose() { __asm jmp dword ptr [g_winmm + 388] }
extern "C" __declspec(naked) void p_mixerGetControlDetailsA() { __asm jmp dword ptr [g_winmm + 392] }
extern "C" __declspec(naked) void p_mixerGetControlDetailsW() { __asm jmp dword ptr [g_winmm + 396] }
extern "C" __declspec(naked) void p_mixerGetDevCapsA() { __asm jmp dword ptr [g_winmm + 400] }
extern "C" __declspec(naked) void p_mixerGetDevCapsW() { __asm jmp dword ptr [g_winmm + 404] }
extern "C" __declspec(naked) void p_mixerGetID() { __asm jmp dword ptr [g_winmm + 408] }
extern "C" __declspec(naked) void p_mixerGetLineControlsA() { __asm jmp dword ptr [g_winmm + 412] }
extern "C" __declspec(naked) void p_mixerGetLineControlsW() { __asm jmp dword ptr [g_winmm + 416] }
extern "C" __declspec(naked) void p_mixerGetLineInfoA() { __asm jmp dword ptr [g_winmm + 420] }
extern "C" __declspec(naked) void p_mixerGetLineInfoW() { __asm jmp dword ptr [g_winmm + 424] }
extern "C" __declspec(naked) void p_mixerGetNumDevs() { __asm jmp dword ptr [g_winmm + 428] }
extern "C" __declspec(naked) void p_mixerMessage() { __asm jmp dword ptr [g_winmm + 432] }
extern "C" __declspec(naked) void p_mixerOpen() { __asm jmp dword ptr [g_winmm + 436] }
extern "C" __declspec(naked) void p_mixerSetControlDetails() { __asm jmp dword ptr [g_winmm + 440] }
extern "C" __declspec(naked) void p_mmDrvInstall() { __asm jmp dword ptr [g_winmm + 444] }
extern "C" __declspec(naked) void p_mmGetCurrentTask() { __asm jmp dword ptr [g_winmm + 448] }
extern "C" __declspec(naked) void p_mmTaskBlock() { __asm jmp dword ptr [g_winmm + 452] }
extern "C" __declspec(naked) void p_mmTaskCreate() { __asm jmp dword ptr [g_winmm + 456] }
extern "C" __declspec(naked) void p_mmTaskSignal() { __asm jmp dword ptr [g_winmm + 460] }
extern "C" __declspec(naked) void p_mmTaskYield() { __asm jmp dword ptr [g_winmm + 464] }
extern "C" __declspec(naked) void p_mmioAdvance() { __asm jmp dword ptr [g_winmm + 468] }
extern "C" __declspec(naked) void p_mmioAscend() { __asm jmp dword ptr [g_winmm + 472] }
extern "C" __declspec(naked) void p_mmioClose() { __asm jmp dword ptr [g_winmm + 476] }
extern "C" __declspec(naked) void p_mmioCreateChunk() { __asm jmp dword ptr [g_winmm + 480] }
extern "C" __declspec(naked) void p_mmioDescend() { __asm jmp dword ptr [g_winmm + 484] }
extern "C" __declspec(naked) void p_mmioFlush() { __asm jmp dword ptr [g_winmm + 488] }
extern "C" __declspec(naked) void p_mmioGetInfo() { __asm jmp dword ptr [g_winmm + 492] }
extern "C" __declspec(naked) void p_mmioInstallIOProcA() { __asm jmp dword ptr [g_winmm + 496] }
extern "C" __declspec(naked) void p_mmioInstallIOProcW() { __asm jmp dword ptr [g_winmm + 500] }
extern "C" __declspec(naked) void p_mmioOpenA() { __asm jmp dword ptr [g_winmm + 504] }
extern "C" __declspec(naked) void p_mmioOpenW() { __asm jmp dword ptr [g_winmm + 508] }
extern "C" __declspec(naked) void p_mmioRead() { __asm jmp dword ptr [g_winmm + 512] }
extern "C" __declspec(naked) void p_mmioRenameA() { __asm jmp dword ptr [g_winmm + 516] }
extern "C" __declspec(naked) void p_mmioRenameW() { __asm jmp dword ptr [g_winmm + 520] }
extern "C" __declspec(naked) void p_mmioSeek() { __asm jmp dword ptr [g_winmm + 524] }
extern "C" __declspec(naked) void p_mmioSendMessage() { __asm jmp dword ptr [g_winmm + 528] }
extern "C" __declspec(naked) void p_mmioSetBuffer() { __asm jmp dword ptr [g_winmm + 532] }
extern "C" __declspec(naked) void p_mmioSetInfo() { __asm jmp dword ptr [g_winmm + 536] }
extern "C" __declspec(naked) void p_mmioStringToFOURCCA() { __asm jmp dword ptr [g_winmm + 540] }
extern "C" __declspec(naked) void p_mmioStringToFOURCCW() { __asm jmp dword ptr [g_winmm + 544] }
extern "C" __declspec(naked) void p_mmioWrite() { __asm jmp dword ptr [g_winmm + 548] }
extern "C" __declspec(naked) void p_mmsystemGetVersion() { __asm jmp dword ptr [g_winmm + 552] }
extern "C" __declspec(naked) void p_mod32Message() { __asm jmp dword ptr [g_winmm + 556] }
extern "C" __declspec(naked) void p_mxd32Message() { __asm jmp dword ptr [g_winmm + 560] }
extern "C" __declspec(naked) void p_sndPlaySoundA() { __asm jmp dword ptr [g_winmm + 564] }
extern "C" __declspec(naked) void p_sndPlaySoundW() { __asm jmp dword ptr [g_winmm + 568] }
extern "C" __declspec(naked) void p_tid32Message() { __asm jmp dword ptr [g_winmm + 572] }
extern "C" __declspec(naked) void p_timeBeginPeriod() { __asm jmp dword ptr [g_winmm + 576] }
extern "C" __declspec(naked) void p_timeEndPeriod() { __asm jmp dword ptr [g_winmm + 580] }
extern "C" __declspec(naked) void p_timeGetDevCaps() { __asm jmp dword ptr [g_winmm + 584] }
extern "C" __declspec(naked) void p_timeGetSystemTime() { __asm jmp dword ptr [g_winmm + 588] }
extern "C" __declspec(naked) void p_timeGetTime() { __asm jmp dword ptr [g_winmm + 592] }
extern "C" __declspec(naked) void p_timeKillEvent() { __asm jmp dword ptr [g_winmm + 596] }
extern "C" __declspec(naked) void p_timeSetEvent() { __asm jmp dword ptr [g_winmm + 600] }
extern "C" __declspec(naked) void p_waveInAddBuffer() { __asm jmp dword ptr [g_winmm + 604] }
extern "C" __declspec(naked) void p_waveInClose() { __asm jmp dword ptr [g_winmm + 608] }
extern "C" __declspec(naked) void p_waveInGetDevCapsA() { __asm jmp dword ptr [g_winmm + 612] }
extern "C" __declspec(naked) void p_waveInGetDevCapsW() { __asm jmp dword ptr [g_winmm + 616] }
extern "C" __declspec(naked) void p_waveInGetErrorTextA() { __asm jmp dword ptr [g_winmm + 620] }
extern "C" __declspec(naked) void p_waveInGetErrorTextW() { __asm jmp dword ptr [g_winmm + 624] }
extern "C" __declspec(naked) void p_waveInGetID() { __asm jmp dword ptr [g_winmm + 628] }
extern "C" __declspec(naked) void p_waveInGetNumDevs() { __asm jmp dword ptr [g_winmm + 632] }
extern "C" __declspec(naked) void p_waveInGetPosition() { __asm jmp dword ptr [g_winmm + 636] }
extern "C" __declspec(naked) void p_waveInMessage() { __asm jmp dword ptr [g_winmm + 640] }
extern "C" __declspec(naked) void p_waveInOpen() { __asm jmp dword ptr [g_winmm + 644] }
extern "C" __declspec(naked) void p_waveInPrepareHeader() { __asm jmp dword ptr [g_winmm + 648] }
extern "C" __declspec(naked) void p_waveInReset() { __asm jmp dword ptr [g_winmm + 652] }
extern "C" __declspec(naked) void p_waveInStart() { __asm jmp dword ptr [g_winmm + 656] }
extern "C" __declspec(naked) void p_waveInStop() { __asm jmp dword ptr [g_winmm + 660] }
extern "C" __declspec(naked) void p_waveInUnprepareHeader() { __asm jmp dword ptr [g_winmm + 664] }
extern "C" __declspec(naked) void p_waveOutBreakLoop() { __asm jmp dword ptr [g_winmm + 668] }
extern "C" __declspec(naked) void p_waveOutClose() { __asm jmp dword ptr [g_winmm + 672] }
extern "C" __declspec(naked) void p_waveOutGetDevCapsA() { __asm jmp dword ptr [g_winmm + 676] }
extern "C" __declspec(naked) void p_waveOutGetDevCapsW() { __asm jmp dword ptr [g_winmm + 680] }
extern "C" __declspec(naked) void p_waveOutGetErrorTextA() { __asm jmp dword ptr [g_winmm + 684] }
extern "C" __declspec(naked) void p_waveOutGetErrorTextW() { __asm jmp dword ptr [g_winmm + 688] }
extern "C" __declspec(naked) void p_waveOutGetID() { __asm jmp dword ptr [g_winmm + 692] }
extern "C" __declspec(naked) void p_waveOutGetNumDevs() { __asm jmp dword ptr [g_winmm + 696] }
extern "C" __declspec(naked) void p_waveOutGetPitch() { __asm jmp dword ptr [g_winmm + 700] }
extern "C" __declspec(naked) void p_waveOutGetPlaybackRate() { __asm jmp dword ptr [g_winmm + 704] }
extern "C" __declspec(naked) void p_waveOutGetPosition() { __asm jmp dword ptr [g_winmm + 708] }
extern "C" __declspec(naked) void p_waveOutGetVolume() { __asm jmp dword ptr [g_winmm + 712] }
extern "C" __declspec(naked) void p_waveOutMessage() { __asm jmp dword ptr [g_winmm + 716] }
extern "C" __declspec(naked) void p_waveOutOpen() { __asm jmp dword ptr [g_winmm + 720] }
extern "C" __declspec(naked) void p_waveOutPause() { __asm jmp dword ptr [g_winmm + 724] }
extern "C" __declspec(naked) void p_waveOutPrepareHeader() { __asm jmp dword ptr [g_winmm + 728] }
extern "C" __declspec(naked) void p_waveOutReset() { __asm jmp dword ptr [g_winmm + 732] }
extern "C" __declspec(naked) void p_waveOutRestart() { __asm jmp dword ptr [g_winmm + 736] }
extern "C" __declspec(naked) void p_waveOutSetPitch() { __asm jmp dword ptr [g_winmm + 740] }
extern "C" __declspec(naked) void p_waveOutSetPlaybackRate() { __asm jmp dword ptr [g_winmm + 744] }
extern "C" __declspec(naked) void p_waveOutSetVolume() { __asm jmp dword ptr [g_winmm + 748] }
extern "C" __declspec(naked) void p_waveOutUnprepareHeader() { __asm jmp dword ptr [g_winmm + 752] }
extern "C" __declspec(naked) void p_waveOutWrite() { __asm jmp dword ptr [g_winmm + 756] }
extern "C" __declspec(naked) void p_wid32Message() { __asm jmp dword ptr [g_winmm + 760] }
extern "C" __declspec(naked) void p_wod32Message() { __asm jmp dword ptr [g_winmm + 764] }
